# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ahmed Abu Taha
email: ahmedmabutaha@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I’m Ahmed Abu Taha, entrepreneur and a self-taught full-stack web developer. 
  Interested in all-things entrepreneurship, education reform, technology, design,
  coding and much more…

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter: ahmedabutaha
github:  ahmedmabutaha
facebook: ahmedabtaha
instagram: ahmedabutaha
linkedin: ahmedabutaha

# Build settings
markdown: kramdown

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
